### ISSUE TITLE
'punycode' deprecated

### ISSUE THREAD

**Issue by RomanticBarracks** [wen-moon-ser/moonshot-bot-examples#5]
PS C:\moon\src> ts-node buyIx.ts
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)
(node:20268) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

punycode deprecated when run buyIx.ts. Any solutions?

**Comment by mavagio** [comment]
please try again with the latest release, and make sure you remove the node-modules folder and install all dependents again
